USE [master]
GO

/****** Object:  Database [GeoCultureDB]    Script Date: 4/18/2014 7:28:04 PM ******/
CREATE DATABASE [GeoCultureDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GeoCultureDB', FILENAME = N'E:\MSSQL\MSSQL11.CARL\MSSQL\DATA\GeoCultureDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GeoCultureDB_log', FILENAME = N'E:\MSSQL\MSSQL11.CARL\MSSQL\DATA\GeoCultureDB_log.ldf' , SIZE = 4672KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GeoCultureDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GeoCultureDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GeoCultureDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GeoCultureDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GeoCultureDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GeoCultureDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GeoCultureDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [GeoCultureDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GeoCultureDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [GeoCultureDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GeoCultureDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GeoCultureDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GeoCultureDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GeoCultureDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GeoCultureDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GeoCultureDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GeoCultureDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GeoCultureDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GeoCultureDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GeoCultureDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GeoCultureDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GeoCultureDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GeoCultureDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GeoCultureDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GeoCultureDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GeoCultureDB] SET RECOVERY FULL 
GO

ALTER DATABASE [GeoCultureDB] SET  MULTI_USER 
GO

ALTER DATABASE [GeoCultureDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GeoCultureDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GeoCultureDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GeoCultureDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GeoCultureDB] SET  READ_WRITE 
GO


USE [GeoCultureDB]
GO

/****** Object:  Table [dbo].[InstitutionBaseInfo]    Script Date: 4/18/2014 7:28:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[InstitutionBaseInfo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](300) NOT NULL,
	[Address] [nvarchar](100) NOT NULL,
	[Latitude] [float] NOT NULL,
	[Longitude] [float] NOT NULL,
	[Email] [nvarchar](50) NULL,
	[PhoneNumber] [nvarchar](50) NULL,
	[TypeId] [int] NOT NULL,
	[Site] [nvarchar](50) NULL,
	[WorkingHours] [nvarchar](150) NULL,
 CONSTRAINT [PK_InstitutionBaseInfo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [GeoCultureDB]
GO

/****** Object:  Table [dbo].[InstitutionType]    Script Date: 4/18/2014 7:28:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[InstitutionType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TypeName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_InstitutionType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE [dbo].[InstitutionBaseInfo]  WITH CHECK ADD  CONSTRAINT [FK_InstitutionBaseInfo_InstitutionType] FOREIGN KEY([TypeId])
REFERENCES [dbo].[InstitutionType] ([Id])
GO

ALTER TABLE [dbo].[InstitutionBaseInfo] CHECK CONSTRAINT [FK_InstitutionBaseInfo_InstitutionType]
GO

